"""B2 — wrapper-boundary benchmark (2026-08-03 refresh campaign).

Re-measures the deck's wrapper-boundary claim ("BitSet dominates tiny support;
8-12 transitional; CM modestly ahead at controlled live_k=16") on post-repair
code. CM wrapper total (materialize_hybrid_no_reinflate, flat+words) vs bare
BitSet (eval_expr_words_bitset) at live_k in {4,6,8,10,12,16}, cached and
uncached regimes, with wrapper-overhead decomposition.

Corpus: fresh, deterministic (blake2b seeds, no hash()), admitted with the
corrected-E3 rules (exact semantic support, measured family/shape membership,
distinct structural hash + truth SHA per stratum), generated by importing the
frozen driver ``cm_gap_e3_corrected_2026_08_02.py`` as a library. The
semantic profile here uses the bigint raw-AST evaluator (works at every k,
including k<6 where the words engine falls back).

Regimes:
- cached: node/program objects prebuilt, programs attached (steady-state reuse).
- uncached (k>=6 only; labelled warmenv — warm process/global caches, fresh
  per-call compile of both sides): CM = compile_expr_to_cm_ir + lower + eval;
  BitSet = compile_expr_flat + eval. At k=4 the words engine falls back to the
  bigint path and per-call recompilation is not separable from parse caching;
  recorded as skipped_uncached_k_lt_6.

Blocked/paired interleaved rounds; packed equality across wrapper, bare
BitSet, CSE reference, and bigint reference before any timing. Outputs are
refuse-overwrite. Blocked schedule only (single-formula paired alternation, as
in Audit V4's packed-eval protocol); no round-robin pooling exists to confuse.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import importlib.util
import json
import math
import platform
import random
import statistics
import subprocess
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.setrecursionlimit(200_000)

import numpy as np

from bitset_backend import (
    _eval_words,
    bitset_to_bool_array,
    compile_expr_cse,
    compile_expr_flat,
    eval_expr_flat_bitset,
    eval_expr_words_bitset,
    get_expr_flat_program,
    get_flat_program,
    program_metrics,
)
from cm_expr_serde import expr_from_json, expr_to_json_dag
from cm_ir import compile_expr_to_cm_ir, expr_structural_hash, materialize_hybrid_no_reinflate

_spec = importlib.util.spec_from_file_location(
    "e3c_frozen", ROOT / "deliverables_n22_24" / "cm_gap_e3_corrected_2026_08_02.py")
e3c = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(e3c)

GENERATOR_VERSION = "b2-wrapper-2026-08-03.1"
STRATA = (4, 6, 8, 10, 12, 16)
ROUNDS = 7
WORDS_MIN = 6


def stable_seed(k: int, family: str, shape: str, attempt: int) -> int:
    tag = (f"{GENERATOR_VERSION}|k={k}|family={e3c.FAMILY_CODES[family]}"
           f"|shape={e3c.SHAPE_CODES[shape]}|attempt={attempt}")
    return int.from_bytes(hashlib.blake2b(tag.encode(), digest_size=8).digest(), "big") >> 1


def semantic_profile_bigint(expr, k):
    """Exact semantic support + truth SHA via the raw-AST bigint evaluator."""
    vars_key = tuple(f"x{i}" for i in range(k))
    bits = eval_expr_flat_bitset(expr, vars_key)
    arr = bitset_to_bool_array(bits, k)
    cube = arr.reshape((2,) * k)
    dep = [ax for ax in range(k)
           if not np.array_equal(np.take(cube, 0, axis=ax), np.take(cube, 1, axis=ax))]
    nbytes = max(1, (1 << k) // 8)
    truth_sha = hashlib.sha256(int(bits).to_bytes(nbytes, "little")).hexdigest()
    return dep, truth_sha, bits


def build_corpus(per_cell, max_attempts, log=print):
    records, rejection_stats = [], {}
    for k in STRATA:
        stratum_hashes, stratum_truths = set(), set()
        for family, weights in e3c.FAMILIES.items():
            for shape in ("tree", "shared"):
                made, attempt = 0, 0
                rejects = Counter()
                while made < per_cell and attempt < max_attempts:
                    attempt += 1
                    seed = stable_seed(k, family, shape, attempt)
                    rng = random.Random(seed)
                    expr = (e3c.tree_formula if shape == "tree"
                            else e3c.shared_formula)(rng, k, weights)
                    if len(e3c.syntactic_support(expr)) != k:
                        rejects["syntactic_support"] += 1; continue
                    struct = e3c.analyze_structure(expr)
                    if struct["unfolded_occurrences"] > e3c.MAX_UNFOLDED:
                        rejects["unfolded_cap"] += 1; continue
                    if shape == "tree" and struct["n_repeated_nonleaf_structural"] > 0:
                        rejects["tree_repeated_nonleaf"] += 1; continue
                    if shape == "shared" and struct["sharing_factor"] < e3c.SHARED_MIN_SHARING:
                        rejects["shared_low_sharing"] += 1; continue
                    fam = e3c.family_admission(struct["operator_mix_structural"])
                    if family not in fam["actual_families"]:
                        rejects["family_membership"] += 1; continue
                    dep, truth_sha, bits_ref = semantic_profile_bigint(expr, k)
                    if not dep:
                        rejects["constant"] += 1; continue
                    if dep != list(range(k)):
                        rejects["semantic_support"] += 1; continue
                    h = expr_structural_hash(expr)
                    if h in stratum_hashes:
                        rejects["dup_structural_hash"] += 1; continue
                    if truth_sha in stratum_truths:
                        rejects["dup_truth_function"] += 1; continue
                    support = tuple(f"x{i}" for i in range(k))
                    wrapped = materialize_hybrid_no_reinflate(
                        compile_expr_to_cm_ir(expr), support, fixed={},
                        hybrid_threshold=16, allow_reduced_output=False,
                        max_full_output_vars=16, flat_eval=True, words_eval=True)
                    if int(wrapped.bits) != int(bits_ref):
                        raise AssertionError(
                            f"CM/bigint truth disagreement at admission: k={k} "
                            f"{family}/{shape} seed={seed}")
                    stratum_hashes.add(h); stratum_truths.add(truth_sha)
                    made += 1
                    records.append({
                        "id": f"b2-k{k}-{family}-{shape}-{made}-{h[:12]}",
                        "generator_version": GENERATOR_VERSION,
                        "stratum_live_k": k, "op_family": family, "shape": shape,
                        "seed": seed, "attempt": attempt,
                        "structural_hash": h, "truth_sha256": truth_sha,
                        "semantic_support_indices": dep,
                        "family_admission": fam, **struct,
                        "expression_v2": expr_to_json_dag(expr),
                    })
                rejection_stats[f"k{k}/{family}/{shape}"] = {
                    "attempts": attempt, "admitted": made, "rejects": dict(rejects),
                    "exhausted": made < per_cell}
                log(f"  cell k={k}/{family}/{shape}: {made}/{per_cell} in {attempt} attempts")
    return records, rejection_stats


def timed(fn, repeats=1, blocks=3):
    best = float("inf")
    for _ in range(blocks):
        t0 = time.perf_counter()
        for _ in range(repeats):
            fn()
        best = min(best, (time.perf_counter() - t0) / repeats)
    return best


def measure(rec):
    k = rec["stratum_live_k"]
    support = tuple(f"x{i}" for i in range(k))
    expr = expr_from_json(rec["expression_v2"])
    node = compile_expr_to_cm_ir(expr)

    def cm_wrapper():
        return materialize_hybrid_no_reinflate(
            node, support, fixed={}, hybrid_threshold=16,
            allow_reduced_output=False, max_full_output_vars=16,
            flat_eval=True, words_eval=True)

    def bs_bare():
        return eval_expr_words_bitset(expr, support)

    # packed equality across wrapper, bare bitset, CSE reference, bigint reference
    ref = int(eval_expr_flat_bitset(expr, support))
    if int(cm_wrapper().bits) != ref or int(bs_bare()) != ref:
        raise AssertionError(f"packed mismatch: {rec['id']}")
    if k >= WORDS_MIN:
        if int(_eval_words(compile_expr_cse(expr), support, {})) != ref:
            raise AssertionError(f"CSE mismatch: {rec['id']}")
    nbytes = max(1, (1 << k) // 8)
    if hashlib.sha256(ref.to_bytes(nbytes, "little")).hexdigest() != rec["truth_sha256"]:
        raise AssertionError(f"truth drift vs corpus: {rec['id']}")

    row = {f: rec[f] for f in ("id", "stratum_live_k", "op_family", "shape",
                               "structural_hash", "truth_sha256",
                               "structural_dag_nodes", "unfolded_occurrences")}
    row["packed_equal_all_arms"] = True
    prog_cm = get_flat_program(node)
    row["cm_flat_instructions"] = program_metrics(prog_cm)["flat_instructions"]
    row["bitset_engine"] = "words" if k >= WORDS_MIN else "bigint_fallback"

    est = timed(cm_wrapper, 3)
    repeat = 200 if est < 50e-6 else 50 if est < 500e-6 else 10
    row["repeat"] = repeat
    cached_ratios, cm_t, bs_t = [], [], []
    for rnd in range(ROUNDS):
        if rnd % 2:
            c = timed(cm_wrapper, repeat, blocks=1); b = timed(bs_bare, repeat, blocks=1)
        else:
            b = timed(bs_bare, repeat, blocks=1); c = timed(cm_wrapper, repeat, blocks=1)
        cached_ratios.append(c / b); cm_t.append(c); bs_t.append(b)
    row["cached_cm_wrapper_us"] = statistics.median(cm_t) * 1e6
    row["cached_bitset_us"] = statistics.median(bs_t) * 1e6
    row["cached_ratio_median"] = statistics.median(cached_ratios)
    row["cached_ratios"] = cached_ratios

    # decomposition (cached regime)
    if k >= WORDS_MIN:
        row["cm_kernel_us"] = timed(lambda: _eval_words(prog_cm, support, {}),
                                    repeat, blocks=2) * 1e6
        row["wrapper_overhead_us"] = row["cached_cm_wrapper_us"] - row["cm_kernel_us"]
        row["bs_kernel_us"] = timed(
            lambda: _eval_words(get_expr_flat_program(expr), support, {}),
            repeat, blocks=2) * 1e6
    row["cm_prep_us"] = timed(lambda: compile_expr_to_cm_ir(expr)) * 1e6

    # uncached (warmenv) regime, k >= 6 only
    if k >= WORDS_MIN:
        def cm_uncached():
            n = compile_expr_to_cm_ir(expr)
            from bitset_backend import compile_flat
            return _eval_words(compile_flat(n), support, {})

        def bs_uncached():
            return _eval_words(compile_expr_flat(expr), support, {})

        un_ratios, uc_t, ub_t = [], [], []
        reps_u = max(3, repeat // 10)
        for rnd in range(ROUNDS):
            if rnd % 2:
                c = timed(cm_uncached, reps_u, blocks=1); b = timed(bs_uncached, reps_u, blocks=1)
            else:
                b = timed(bs_uncached, reps_u, blocks=1); c = timed(cm_uncached, reps_u, blocks=1)
            un_ratios.append(c / b); uc_t.append(c); ub_t.append(b)
        row["uncached_cm_us"] = statistics.median(uc_t) * 1e6
        row["uncached_bitset_us"] = statistics.median(ub_t) * 1e6
        row["uncached_ratio_median"] = statistics.median(un_ratios)
        row["uncached_ratios"] = un_ratios
        row["uncached_status"] = "ok"
    else:
        row["uncached_status"] = "skipped_uncached_k_lt_6"
    return row


def pct(vals, q):
    return float(np.percentile(np.asarray(vals, dtype=float), q))


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--per-cell", type=int, default=2)
    ap.add_argument("--max-attempts", type=int, default=800)
    args = ap.parse_args(argv)
    out = Path(args.out_dir)
    targets = {name: out / name for name in (
        "CM_b2_wrapper_corpus_2026_08_03.jsonl",
        "cm_b2_wrapper_results_2026_08_03.json",
        "CM_b2_wrapper_summary_2026_08_03.csv")}
    existing = [str(p) for p in targets.values() if p.exists()]
    if existing:
        raise SystemExit("refusing to overwrite:\n  " + "\n  ".join(existing))
    out.mkdir(parents=True, exist_ok=True)

    t0 = time.perf_counter()
    print("generating B2 corpus ...", flush=True)
    corpus, rejection_stats = build_corpus(args.per_cell, args.max_attempts)
    meta_line = {"record_type": "b2_wrapper_corpus_meta",
                 "generator_version": GENERATOR_VERSION, "strata": list(STRATA),
                 "per_cell": args.per_cell, "rejection_stats": rejection_stats}
    lines = [json.dumps(meta_line, sort_keys=True, separators=(",", ":"))]
    lines += [json.dumps(r, sort_keys=True, separators=(",", ":")) for r in corpus]
    corpus_bytes = ("\n".join(lines) + "\n").encode()
    targets["CM_b2_wrapper_corpus_2026_08_03.jsonl"].write_bytes(corpus_bytes)
    corpus_sha = hashlib.sha256(corpus_bytes).hexdigest()
    print(f"corpus: {len(corpus)} formulas, sha256 {corpus_sha}")

    rows = []
    for rec in corpus:
        rows.append(measure(rec))
        if len(rows) % 16 == 0:
            print(f"  measured {len(rows)}/{len(corpus)}", flush=True)

    summary = []
    for k in STRATA:
        sel = [r for r in rows if r["stratum_live_k"] == k]
        if not sel:
            continue
        for regime, key in (("cached", "cached_ratio_median"),
                            ("uncached_warmenv", "uncached_ratio_median")):
            rsel = [r for r in sel if key in r]
            if not rsel:
                continue
            ratios = [r[key] for r in rsel]
            entry = {
                "live_k": k, "regime": regime, "n_formulas": len(rsel),
                "ratio_median": statistics.median(ratios),
                "ratio_geomean": math.exp(statistics.mean(math.log(x) for x in ratios)),
                "ratio_p10": pct(ratios, 10), "ratio_p90": pct(ratios, 90),
            }
            if regime == "cached":
                entry["cm_wrapper_us_median"] = statistics.median(
                    r["cached_cm_wrapper_us"] for r in rsel)
                entry["bitset_us_median"] = statistics.median(
                    r["cached_bitset_us"] for r in rsel)
                ov = [r["wrapper_overhead_us"] for r in rsel if "wrapper_overhead_us" in r]
                entry["wrapper_overhead_us_median"] = statistics.median(ov) if ov else None
            summary.append(entry)

    try:
        git_rev = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT,
                                 capture_output=True, text=True).stdout.strip()
    except Exception:
        git_rev = "unknown"
    results = {
        "_meta": {
            "driver": Path(__file__).name, "generator_version": GENERATOR_VERSION,
            "python": sys.version, "numpy": np.__version__,
            "cpu": platform.processor(), "platform": platform.platform(),
            "git_revision": git_rev,
            "created_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "wall_time_s": time.perf_counter() - t0,
            "corpus_sha256": corpus_sha, "rounds": ROUNDS,
            "regimes": "cached (prebuilt node/programs) and uncached warmenv (fresh "
                       "per-call compile, warm process/global caches; k>=6 only)",
            "schedule": "blocked paired interleaved, order alternating per round",
            "rejection_stats": rejection_stats,
            "note": "wrapper hybrid_threshold=16, flat+words; bitset control is "
                    "eval_expr_words_bitset (bigint fallback below 6 vars)",
        },
        "formulas": rows,
        "summary": summary,
    }
    targets["cm_b2_wrapper_results_2026_08_03.json"].write_text(
        json.dumps(results, indent=2), encoding="utf-8")
    with targets["CM_b2_wrapper_summary_2026_08_03.csv"].open("w", newline="",
                                                              encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(summary[0]), extrasaction="ignore")
        w.writeheader(); w.writerows(summary)
    print(f"wall {time.perf_counter() - t0:.1f}s; wrote 3 outputs to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
