// Generated by scripts/generate_v4audit_public_chart_data.py; do not hand edit.
const V4AUDIT_CHART_DATA = {
  "frontier": {
    "beyond_guard_support": [
      null,
      null,
      null,
      null,
      0.96,
      null,
      0.97,
      null,
      0.97
    ],
    "corrected_all_live": [
      0.48,
      0.53,
      0.57,
      0.48,
      0.4,
      0.53,
      null,
      null,
      null
    ],
    "n": [
      16,
      18,
      20,
      22,
      24,
      26,
      28,
      30,
      32
    ]
  },
  "kernel": {
    "bigint_engine": [
      0.56,
      0.85,
      0.89,
      0.96,
      0.87
    ],
    "n": [
      16,
      18,
      20,
      22,
      24
    ],
    "words_engine": [
      0.9,
      0.89,
      0.96,
      0.94,
      1.04
    ]
  },
  "schema_version": 1,
  "source_revision": "5dd6ec77b31839b291aa1785b9ff218c83591380",
  "sources": {
    "CM_FABLE_BENCHMARKS_2026-07-21.md": {
      "rule": "documented Audit V3 paired rerun n=16..24",
      "sha256": "03d07d9de036d4269b8c03f2a2a45d181cf0ab4618044700559f9e08780db474"
    },
    "CM_FABLE_comprehensive_beyondguard.csv": {
      "rule": "median ratio_words by n, rounded 2dp",
      "sha256": "9b8ac0afd55def142a19863004defaf8607693a53c4f65c898fccf8f84c7cd21"
    },
    "CM_FABLE_cudd_wrapper32_summary.csv": {
      "rule": "ratio_cudd_build_bitset_median, rounded 2dp; contextual metric",
      "sha256": "9ddae24512ca10ed2e82cd33ce444996127819e8ec6b0091e727a0aae684b8f7"
    },
    "CM_FABLE_extended_n32_summary.csv": {
      "rule": "depth=4 ratio_median n=26..32, rounded 2dp",
      "sha256": "26ea2873073db7576e5d0d73fc068cfd843bd4563b5c425642e1f528a11bed9b"
    },
    "CM_V3AUDIT_F1_words_timing.csv": {
      "rule": "Python 3.13.5 CM median / raw median, rounded 2dp",
      "sha256": "31ea0bc7302399eb6b1de0de03d0d53807f29b3fcd6a554410d006e0ed5e026a"
    },
    "CM_V3AUDIT_F5_corrected_all_live_summary.csv": {
      "rule": "cm_over_bitset_median, rounded 2dp",
      "sha256": "421efad3660daa602e146a831f745b5658a6cd2306d127cb707c1fc004473a00"
    }
  },
  "wrapper": {
    "cm_over_bitset": [
      1.05,
      1.27,
      1.23,
      1.15,
      1.05,
      0.98,
      0.92,
      0.89,
      0.84
    ],
    "cudd_build_over_bitset_contextual": [
      0.63,
      4.4,
      4.62,
      4.81,
      3.41,
      3.34,
      3.18,
      3.19,
      3.24
    ],
    "n": [
      16,
      18,
      20,
      22,
      24,
      26,
      28,
      30,
      32
    ]
  }
};
