"""Authored advanced lessons, with explicit teaching states and source ownership."""
from pathlib import Path
import json
OUT=Path(__file__).resolve().parent/'deep_series/advanced_cm_tutorial_series_v1'
LESSONS=[]
OPS={'⇒':[[1,0],[1,1]],'⇐':[[1,1],[0,1]],'∧':[[1,0],[0,0]],'∨':[[1,1],[1,0]],'⇕':[[0,1],[1,0]],'⇔':[[1,0],[0,1]],'⇑':[[0,1],[0,0]],'⇓':[[0,0],[1,0]],'¬∧':[[0,1],[1,1]],'¬∨':[[0,0],[0,1]],'¬R':[[0,1],[0,1]],'¬L':[[0,0],[1,1]],'0':[[0,0],[0,0]]}
def mat(name,values=None,rows=None,cols=None,mark=None):
    return dict(name='['+name+']' if name in OPS else name,values=OPS.get(name) if values is None else values,rows=rows or ['1','0'],cols=cols or ['1','0'],mark=mark)
def panel(label,*lines):return dict(label=label,lines=list(lines))
def scene(title,text,equations,cards,note,question=False):
    return dict(title=title,text=text,equations=equations,cards=cards,note=note,visual='advanced',question=question,**({'pause':5} if question else {}))
def lesson(slug,title,prereq,source,scenes):
    LESSONS.append(dict(id=f'{len(LESSONS)+10:02d}_{slug}',title=title,objective=scenes[-1]['note'],prerequisite=prereq,source=source,scenes=scenes))
S=scene;P=panel;M=mat
lesson('transpose','Swap operands by transposing a CM','Foundations 3–4: numeric and symbolic measurements.','Paper §3.1, pp.8–9',[
S('Does reversing the inputs change the rule?', 'If X implies Y, does Y imply X? Not in general. Today we will reverse the operands and see exactly which matrix entries move. We keep the true-first convention: the first row and first column mean one.', ['X ⇒ Y   versus   Y ⇒ X'],[M('⇒'),P('QUESTION','Same two inputs','Different order','Can the answer change?')],'Read rows as the left input and columns as the right input.'),
S('Locate the only failure','Implication fails only when its left input is one and its right input is zero. That is the upper-right cell. For X equal to one and Y equal to zero, X implies Y is false, while Y implies X is true.', ['X=1, Y=0','X⇒Y = 0     Y⇒X = 1'],[M('⇒',mark=[0,1]),P('READ THE CELL','Row X=1','Column Y=0','The original result is 0')],'The order of operands matters for implication.'),
S('Transpose: exchange row and column indices','A transpose exchanges the row and column indices of every entry. Diagonal entries stay where they are. The upper-right zero moves to the lower-left position. We have now made the matrix of reverse implication under the original X-row and Y-column labels.', ['Tᵀ[j,i] = T[i,j]','[⇒]ᵀ = [⇐]'],[M('⇒',mark=[0,1]),M('⇐',mark=[1,0])],'The transpose moves each cell from (i,j) to (j,i).'),
S('Keep the measurement identity visible','There are two ways to ask the reversed question. We can put Y on the left of the original implication matrix and X on its right. Or keep X on the left and Y on the right, while transposing the matrix. Both ask whether Y implies X.', ['⟨Y|[⇒]|X⟩ = ⟨X|[⇐]|Y⟩','Y⇒X = X⇐Y'],[M('⇒'),M('⇐')],'Reverse operands, or transpose the matrix: the answers agree.'),
S('Calculate the reversed example','Use X equal to one and Y equal to zero again. With X on the left of the reverse-implication matrix, the bra selects its first row, one, one. Ket zero selects the second entry. The result is one, agreeing with zero implies one.', ['⟨1|[⇐]|0⟩ = [1,1] [0,1]ᵀ','= (1∧0) ⇕ (1∧1) = 1'],[M('⇐',mark=[0,1]),P('VECTORS','⟨1| = [1,0]','|0⟩ = [0,1]ᵀ')],'The reversed result is 1.'),
S('A symmetric operator stays the same','Exclusive-or is different: its matrix equals its transpose. The two off-diagonal entries are both one. This tells us that swapping the operands preserves the exclusive-or rule for every input pair. Symmetry is visible in the numeric matrix.', ['[⇕]ᵀ = [⇕]','X⇕Y = Y⇕X'],[M('⇕'),P('SYMMETRY CHECK','Compare opposite off-diagonal cells','They agree','All four inputs are covered')],'A symmetric CM represents a commutative binary rule.'),
S('Your turn: transpose twice','Suppose we transpose the implication matrix and then transpose it again. Where does its zero finish? Decide which bracketed operator we recover. Track the entry rather than trying to remember a new transformation rule.', ['([⇒]ᵀ)ᵀ = ?'],[M('⇐',mark=[1,0]),P('PREDICT','One more transpose','Which cell receives the zero?')],'Pause and predict the original operator.',True),
S('Answer: return to the original','The zero moves from lower left back to upper right, so two transposes recover the implication matrix. Every entry returns to its starting coordinates. This also explains why reversing the input order twice recovers the original question.', ['(Tᵀ)ᵀ = T','([⇒]ᵀ)ᵀ = [⇒]'],[M('⇒',mark=[0,1]),P('CHECK','First swap: (i,j) becomes (j,i)','Second swap restores (i,j)')],'Two transposes restore the matrix.'),
S('Separate transformation from relabelling','A matrix transformation has to travel with a statement about the operands and axes. Moving entries under fixed axes can change the represented rule. Moving entries and relabelling the inputs together can preserve a measurement. Next we distinguish input negation from output negation.', ['⟨Y|T|X⟩ = ⟨X|Tᵀ|Y⟩'],[P('RECORD BOTH','The numeric entries','The ordered operands'),P('NEXT','Negate the output','Negate one input')],'Explain a transpose with its operand order and labelled axes.')])

lesson('negation','Negate an input, or negate the output','Lesson 10: transpose and ordered operands.','Paper §3.1 and §3.3, pp.8–9,13–14',[
S('Three different meanings of negation','Negating the answer is not the same as negating an input. We will make all three changes to implication: complement its output, negate X, or negate Y. Keep the original matrix visible so we can compare the changes instead of memorizing names.', ['¬(X⇒Y)     (¬X)⇒Y     X⇒(¬Y)'],[M('⇒'),P('THREE ACTIONS','Flip output bits','Swap the X rows','Swap the Y columns')],'Say which quantity is being negated.'),
S('Negate the output: flip every bit','For output negation, turn every zero into one and every one into zero. The sole true result is now X equal to one and Y equal to zero. Its operator is the upward double arrow, meaning X and not Y.', ['¬[⇒] = [⇑]','¬(X⇒Y) = X∧¬Y'],[M('⇒'),M('⇑',mark=[0,1])],'Output complement changes every cell value.'),
S('Negate X: swap the rows','For a negated left input, the new X-equals-one row must use the old X-equals-zero row. The other row swaps in the opposite direction. On implication this produces OR: not X implies Y is equivalent to X or Y.', ['(¬X)⇒Y = X∨Y','Tₓ[i,j] = T[1−i,j]'],[M('⇒',mark=[1,0]),M('∨',mark=[0,0])],'Negating the left input swaps rows under fixed axis labels.'),
S('Negate Y: swap the columns','For a negated right input, swap the columns. The original failure at X one, Y zero is now at X one, Y one. This is NAND: X implies not Y is false only when both X and Y are true.', ['X⇒(¬Y) = ¬(X∧Y)','Tᵧ[i,j] = T[i,1−j]'],[M('⇒'),M('¬∧',mark=[0,0])],'Negating the right input swaps columns.'),
S('Compare all three at one assignment','Let X and Y both be one. Original implication gives one. Negating the output gives zero. Negating only X gives one. Negating only Y gives zero. Two answers happen to agree here, but the complete matrices distinguish the operations.', ['X=1, Y=1'],[M('⇑',mark=[0,0]),M('∨',mark=[0,0]),M('¬∧',mark=[0,0])],'One matching result does not make two rules identical.'),
S('Negate both inputs','Swap both rows and columns to negate both inputs. For a two-by-two array, that has the same effect as a half turn. Implication becomes reverse implication. This is the familiar identity: not X implies not Y is equivalent to Y implies X.', ['(¬X)⇒(¬Y) = Y⇒X','Rotate [⇒] by 180° = [⇐]'],[M('⇒'),M('⇐')],'A half turn negates both inputs in this 2×2 ordering.'),
S('Connect the paper’s rotation notation','The paper writes some input changes as a transpose followed by a rotation. A transpose followed by ninety degrees clockwise swaps columns; a transpose followed by two hundred seventy degrees clockwise swaps rows. The direct row-and-column rule is usually easier to apply.', ['Transpose, then 90° clockwise: swap columns','Transpose, then 270° clockwise: swap rows'],[P('RIGHT INPUT','T[i,1−j]','Column exchange'),P('LEFT INPUT','T[1−i,j]','Row exchange')],'The rotation identities describe the same entry permutations.'),
S('Your turn: complement exclusive-or','Complement every bit of the exclusive-or matrix. Does the new rule accept equal inputs or different inputs? Name the resulting operator if you remember it. You can answer entirely from the two-by-two array.', ['¬[⇕] = ?'],[M('⇕'),P('PREDICT','Flip each 0 and 1','Which input pairs survive?')],'Pause before revealing the complement.',True),
S('Answer: equivalence','Complementing exclusive-or produces equivalence, with ones on the diagonal. Equal inputs are accepted and different inputs are rejected. We can now alter inputs or outputs deliberately. Next we will combine complete matrices, starting with exclusive-or composition.', ['¬[⇕] = [⇔]','¬(X⇕Y) = X⇔Y'],[M('⇕'),M('⇔')],'Distinguish entry complement from row and column permutations.')])

lesson('xor_composition','Compose and decompose over XOR','Foundations 2–4 and lesson 11.','Paper §3.2.1, pp.9–10',[
S('Build OR from smaller rules','Can we build OR from AND and exclusive-or? AND accepts the both-true pair. Exclusive-or accepts the two unequal pairs. Together these three accepted pairs are exactly OR. We will combine the arrays cell by cell and then connect the result to measurements.', ['[∨] = [∧] ⇕ [⇕]'],[M('∧'),M('⇕'),M('∨')],'Here ⇕ between matrices means entrywise exclusive-or.'),
S('Calculate the first row','At the top-left position, one exclusive-or zero gives one. At the top-right position, zero exclusive-or one also gives one. This creates the top row of OR. Each operation uses matching coordinates; there is no row-by-column contraction here.', ['Top left: 1⇕0 = 1','Top right: 0⇕1 = 1'],[M('∧',mark=[0,0]),M('⇕',mark=[0,0]),M('∨',mark=[0,0])],'Combine entries at the same coordinates.'),
S('Complete the second row','The lower-left position gives zero exclusive-or one, or one. The lower-right position gives zero exclusive-or zero, or zero. The result is one, one above one, zero: the numeric OR matrix. We have checked every input pair, not just one example.', ['Bottom left: 0⇕1 = 1','Bottom right: 0⇕0 = 0'],[M('∧',mark=[1,1]),M('⇕',mark=[1,1]),M('∨',mark=[1,1])],'All four positions recover OR.'),
S('Put the same selectors around both sides','With the same bra X and ket Y around every term, the matrix identity becomes an expression identity. Measuring the XOR of the matrices equals XORing their measurements. Boolean AND distributes over exclusive-or, which is why this expansion works.', ['⟨X|([∧]⇕[⇕])|Y⟩','= ⟨X|[∧]|Y⟩ ⇕ ⟨X|[⇕]|Y⟩','= (X∧Y) ⇕ (X⇕Y) = X∨Y'],[P('KEEP FIXED','Left operand X','Right operand Y','Same order in both terms')],'Use the same ordered selectors throughout the decomposition.'),
S('Why XOR is not simply OR','Our first pieces never overlap: AND is true where exclusive-or is false. If pieces overlap, exclusive-or cancels their shared ones. For example, XORing the AND matrix with itself gives the zero matrix. ORing it with itself would preserve AND.', ['[∧] ⇕ [∧] = [0]','1⇕1 = 0     1∨1 = 1'],[M('∧'),M('0')],'Shared ones cancel under XOR.'),
S('Recover a missing piece','If OR equals AND exclusive-or XOR, we can exclusive-or AND into both sides. The two copies of AND cancel, leaving the XOR matrix. This gives a reversible way to recover one unknown piece from the result and the other piece.', ['[∨] ⇕ [∧] = [⇕]','A⇕B=C   implies   B=A⇕C'],[M('∨'),M('∧'),M('⇕')],'XOR lets you recover a missing component uniquely.'),
S('Your turn: cancel an entire matrix','What remains when the exclusive-or matrix is exclusive-ored with itself? Check a diagonal zero and an off-diagonal one. Decide whether any ones survive. This is cancellation of entire arrays through the same scalar rule in every cell.', ['[⇕] ⇕ [⇕] = ?'],[M('⇕'),P('PREDICT','0⇕0 = ?','1⇕1 = ?')],'Pause and apply cancellation entry by entry.',True),
S('Answer: every entry becomes zero','Every entry cancels with its identical partner, so the result is the zero matrix. This applies to every Boolean matrix of a fixed shape. Decomposition is therefore about precisely chosen pieces, not just collecting positive entries without checking their overlap.', ['[⇕] ⇕ [⇕] = [0]','A⇕A = 0'],[M('⇕'),M('0')],'Identical XOR components cancel.'),
S('Choose composition or removal deliberately','We have built OR from disjoint pieces and recovered a missing piece by cancellation. Next we will remove accepted cases using a directional operation. That operation agrees with XOR in our particular containment example, but does not behave like XOR in general.', ['XOR: symmetric difference','Next: A∧¬B, directional removal'],[P('COMPOSITION','Matching dimensions','Matching ordered inputs'),P('NEXT QUESTION','Which accepted cases in A','are absent from B?')],'Use XOR composition with aligned matrices and explicit overlap checks.')])

lesson('quotient','Remove shared features with a CM quotient','Lessons 11–12: complement and entrywise composition.','Paper §3.2.2, pp.10–11',[
S('Remove the both-true case from OR','Suppose OR accepts too many input pairs for our purpose. We want one input or the other, but not both. Removing the cases accepted by AND from those accepted by OR leaves exactly exclusive-or. The paper calls this operation a quotient.', ['A ∖ B := A ∧ ¬B','[∨] ∖ [∧] = ?'],[M('∨'),M('∧')],'The quotient is binary set difference, applied entrywise.'),
S('Define removal on single bits','For each pair of entries, retain the left entry only if the right entry is zero. A left zero stays zero. A shared one is removed. We use a set-minus sign for this binary operation so it cannot be confused with unary negation.', ['a ∖ b = a∧¬b'],[P('FOUR CASES','0∖0=0    0∖1=0','1∖0=1    1∖1=0'),P('MEANING','Keep A','Exclude B')],'This is not division or ordinary integer remainder.'),
S('Complement the matrix to be removed','First complement AND to obtain NAND. Now the both-true cell is zero and the other cells are one. We will AND that array with OR at matching coordinates. The intermediate complement remains visible to make the removal concrete.', ['¬[∧] = [¬∧]','[∨] ∖ [∧] = [∨] ∧ [¬∧]'],[M('∧'),M('¬∧'),M('∨')],'Complement the right operand, then intersect entrywise.'),
S('Compute the retained entries','At the top-left cell, one AND zero removes the both-true case. At each off-diagonal cell, one AND one retains the unequal pair. At the bottom right, zero AND one stays zero. We have recovered exclusive-or by directional removal.', ['11: 1∧0=0     10: 1∧1=1','01: 1∧1=1     00: 0∧1=0'],[M('∨'),M('¬∧'),M('⇕')],'Only the two unequal input pairs survive.'),
S('Compare with XOR carefully','This result also equals OR exclusive-or AND because every case accepted by AND is already accepted by OR. Outside that containment situation, XOR includes cases that occur only in the right operand. Set difference never adds those right-only cases.', ['If B is contained in A: A∖B = A⇕B','Otherwise, the two operations can differ'],[P('XOR','Keep left-only cases','Keep right-only cases'),P('SET DIFFERENCE','Keep left-only cases','Discard right-only cases')],'Containment explains this particular agreement with XOR.'),
S('Your turn: reverse the quotient','Now reverse the order. Remove everything accepted by OR from the AND matrix. Is there a true cell in AND that OR does not already accept? Predict the complete result before calculating it.', ['[∧] ∖ [∨] = ?'],[M('∧'),M('∨')],'Pause and look for an AND-only case.',True),
S('Answer: nothing remains','The only one in AND is also a one in OR, so it is removed. All other AND entries were already zero. The result is the zero matrix. Reversing the quotient changes the answer, while reversing the order of XOR does not.', ['[∧] ∖ [∨] = [0]','[∨] ∖ [∧] = [⇕]'],[M('0'),M('⇕')],'Set difference is directional.'),
S('Translate back to logical expressions','Place the same bra X and ket Y around the quotient. We obtain X or Y, AND not X and Y: exactly the exclusive-or rule. Next we will combine less obviously related expressions, after ensuring that their operand order and negations agree.', ['(X∨Y) ∧ ¬(X∧Y) = X⇕Y','⟨X|([∨]∖[∧])|Y⟩ = ⟨X|[⇕]|Y⟩'],[M('⇕'),P('SOURCE CONVENTION','Paper backslash means A∧¬B','Integer remainder is a different operation')],'Compute a quotient as entrywise A∧¬B and preserve its order.')])

lesson('aligned_composition','Combine rules with a shared ordered basis','Lessons 10–13.','Paper §3.2.3, pp.11–13; independently corrected page-12 examples',[
S('Simplify a pair of complete rules','Consider X implies Y, exclusive-or X or Y. Both expressions use X on the left and Y on the right. We can therefore combine their numeric matrices at matching coordinates. Our aim is to find a simpler rule and check it on every assignment.', ['(X⇒Y) ⇕ (X∨Y)'],[M('⇒'),M('∨')],'Shared ordered operands make entrywise composition meaningful.'),
S('XOR the aligned arrays','Compute one exclusive-or one at the top left, then zero exclusive-or one at the top right. The bottom row similarly becomes zero, one. Both rows are now identical, so the result cannot depend on the left input X.', ['[⇒] ⇕ [∨] = [¬R]'],[M('⇒'),M('∨'),M('¬R')],'Identical rows show that X no longer affects the result.'),
S('Read the remaining right-input rule','The right input Y is one in the first column and zero in the second. The output is zero in the first column and one in the second, so the result is not Y. The paper names this matrix bracket not R, for the complemented right projection.', ['(X⇒Y) ⇕ (X∨Y) = ¬Y'],[M('¬R'),P('ALL FOUR CHECKS','XY=11: 1⇕1=0','XY=10: 0⇕1=1','XY=01: 1⇕1=0','XY=00: 1⇕0=1')],'The result is ¬Y for every assignment.'),
S('Check the manuscript’s printed projection','The printed page-twelve example labels this result not X. Under the declared axes, that is a source discrepancy. Take X zero and Y one: the original expression gives zero, while not X gives one. Our recomputed matrix and truth table agree on not Y.', ['X=0, Y=1: (X⇒Y)⇕(X∨Y)=0','¬X=1     ¬Y=0'],[M('¬R',mark=[1,0]),P('SOURCE NOTE','Page 12 prints ¬X','Verified result under these axes: ¬Y','Original manuscript preserved')],'Verify a printed identity before teaching it.'),
S('Normalize a negated right operand','Now change the first expression to X implies not Y. Its right operand no longer matches the Y in the OR term. Swap the implication matrix columns to absorb the negation. Both terms then have the same bra X and ket Y.', ['X⇒¬Y = ⟨X|[¬∧]|Y⟩','(X⇒¬Y) ⇕ (X∨Y)'],[M('⇒'),M('¬∧'),M('∨')],'Normalize the operand before combining matrices.'),
S('Then combine the normalized rules','NAND exclusive-or OR has ones on the diagonal and zeros off the diagonal. It is equivalence. The paper reaches the same final result, but one intermediate bracket in its printed chain still shows implication. The intermediate array here is explicitly NAND.', ['[¬∧] ⇕ [∨] = [⇔]','(X⇒¬Y) ⇕ (X∨Y) = X⇔Y'],[M('¬∧'),M('∨'),M('⇔')],'The normalized intermediate operator is NAND.'),
S('Your turn: reverse the first implication','What if the expression is Y implies X, exclusive-or X or Y? Rewrite the first term with X as its left selector before combining. Which variable survives, and is it negated? Use the transpose rule from lesson ten.', ['(Y⇒X) ⇕ (X∨Y) = ?'],[M('⇐'),M('∨')],'Pause and combine reverse implication with OR.',True),
S('Answer: the left input is complemented','Reverse implication exclusive-or OR gives zero, zero above one, one. That is the complemented left projection, not X. Compare it with the earlier not Y result: the difference follows directly from which implication we started with.', ['[⇐] ⇕ [∨] = [¬L]','(Y⇒X) ⇕ (X∨Y) = ¬X'],[M('⇐'),M('∨'),M('¬L')],'Normalize order and negations, then compose and verify the result.')])

LM=[['X∧Y','X∧¬Y'],['¬X∧Y','¬X∧¬Y']]
LMI=[['X⇒Y','X⇒¬Y'],['¬X⇒Y','¬X⇒¬Y']]
XL=[['X','X'],['¬X','¬X']];YR=[['Y','¬Y'],['Y','¬Y']]
lesson('lm_factors','Complement and factor logical matrices','Foundations 5 and lessons 11–12.','Paper §4.1.2–4.1.3, pp.16–18; entrywise factor convention made explicit',[
S('A matrix whose entries are expressions','A logical matrix keeps expressions in its cells instead of storing their final truth values. Here M sub X Y means the outer product of ket X and bra Y. Each cell is an AND of one row component and one column component.', ['M_XY = |X⟩⟨Y|'],[M('M_XY',LM),P('SYMBOLIC VECTORS','|X⟩ = [X,¬X]ᵀ','⟨Y| = [Y,¬Y]','No valuation applied yet')],'An LM stores formulas; a numeric CM stores bits.'),
S('Complement each expression','Entrywise complement negates the entire expression in each cell. In the upper-left cell, not X and Y means not the whole conjunction, giving not X or not Y. Apply the same rule to every cell; do not merely negate one input everywhere.', ['¬(X∧Y) = ¬X∨¬Y'],[M('M_XY',LM),M('¬M_XY',[['¬X∨¬Y','¬X∨Y'],['X∨¬Y','X∨Y']])],'Complement the complete formula in each cell.'),
S('Positive valuation connects back to CMs','Set X and Y to one. The original logical matrix becomes the AND correspondence matrix. Its entrywise complement becomes NAND. This connects the symbolic complement to the numeric bit-flipping operation we already know. Keep the order of the cells unchanged.', ['V₊(M_XY) = [∧]','V₊(¬M_XY) = [¬∧]'],[M('∧'),M('¬∧')],'Valuation and entrywise complement agree cell by cell.'),
S('Build the left-only factor','Make a left factor with X repeated across the first row and not X repeated across the second. It is the outer product of ket X and the row one, one. This factor carries the row dependence, while deliberately carrying no Y dependence.', ['M_XL = |X⟩[1,1]'],[M('M_XL',XL),P('LEFT FACTOR','Row dependence: X or ¬X','Same value across each row')],'The left factor varies by row only.'),
S('Build the right-only factor','Make a right factor with Y and not Y in both rows. This is the column one, one times bra Y. It carries the column dependence. We now have two arrays of the same shape, ready to combine at matching positions.', ['M_YR = [1,1]ᵀ⟨Y|'],[M('M_XL',XL),M('M_YR',YR)],'The right factor varies by column only.'),
S('Reconstruct by entrywise AND','AND the factors entry by entry. Top left gives X and Y; top right gives X and not Y. The bottom row gives the other two conjunctions. We explicitly label this entrywise AND because it is different from Boolean row-by-column matrix multiplication.', ['M_XL ∧entry M_YR = M_XY'],[M('M_XL',XL),M('M_YR',YR),M('M_XY',LM)],'Factorization here uses matching cells, with no XOR reduction.'),
S('Why the multiplication convention matters','If we instead used AND-and-exclusive-or matrix multiplication on these factors, the top-left entry would be X and Y exclusive-or X and Y, which is zero. The two identical terms cancel. The paper’s factor notation must therefore be read with the entrywise conjunction convention here.', ['Row-by-column: (X∧Y)⇕(X∧Y)=0','Entrywise: X∧Y'],[P('MATRIX MULTIPLICATION','Pair a row and a column','XOR the paired AND products'),P('ENTRYWISE CONJUNCTION','Pair matching coordinates','One AND at each cell')],'Do not infer a multiplication rule from juxtaposition alone.'),
S('Your turn: one factor cell','Look at the bottom-left cell of the left and right factors. Which formula results from their entrywise AND? Then predict its value when X is zero and Y is one. First form the expression, then evaluate it.', ['Bottom-left entry = ?','Evaluate at X=0, Y=1'],[M('M_XL',XL,mark=[1,0]),M('M_YR',YR,mark=[1,0])],'Pause: construct, then value the cell.',True),
S('Answer: not X and Y','The bottom-left factors are not X and Y, so their conjunction is not X and Y. At X zero and Y one, both factors are true and the entry is one. Next we will use an entire logical matrix between symbolic state vectors.', ['¬X∧Y = ¬0∧1 = 1'],[M('M_XY',LM,mark=[1,0]),P('TWO STAGES','Construct: ¬X∧Y','Evaluate: 1')],'Keep symbolic factors, entrywise operations and valuation separate.')])

lesson('lm_measurement','Measure with a logical matrix','Foundations 3–5 and lesson 15.','Paper §4.1.4, pp.18–19; exhaustive symbolic checks',[
S('Two measurements that look similar','A numeric implication matrix between bra X and ket Y gives the formula X implies Y. An implication logical matrix has formulas inside it too. With state vectors matched to the expressions that define that logical matrix, the measurement can instead simplify to a constant.', ['⟨X|[⇒]|Y⟩ = X⇒Y','Compare: ⟨X|M_{X⇒Y}|Y⟩'],[M('⇒'),M('M_{X⇒Y}',LMI)],'Identify whether the middle object is numeric or symbolic.'),
S('Define the implication LM explicitly','The four cells are X implies Y, X implies not Y, not X implies Y, and not X implies not Y. Bra X is X, not X; ket Y is Y above not Y. X and Y mean the same expressions everywhere in this calculation.', ['⟨X| = [X,¬X]     |Y⟩ = [Y,¬Y]ᵀ'],[M('M_{X⇒Y}',LMI),P('MATCHED EXPRESSIONS','Same X in bra and LM','Same Y in ket and LM','Use AND/XOR matrix arithmetic')],'A matched measurement shares its defining expressions.'),
S('Expand the first intermediate entry','Multiply bra X into the first matrix column. X AND X implies Y simplifies to X and Y. Not X AND not X implies Y simplifies to not X and Y. Exclusive-or the two disjoint terms to get Y.', ['(X∧(¬X∨Y)) ⇕ (¬X∧(X∨Y))','= (X∧Y) ⇕ (¬X∧Y) = Y'],[M('M_{X⇒Y}',LMI,mark=[0,0]),P('FACTOR OUT Y','(X⇕¬X)∧Y','1∧Y = Y')],'The first entry of the intermediate row is Y.'),
S('Expand the second intermediate entry','The second column follows the same calculation with not Y. We obtain X and not Y exclusive-or not X and not Y, which simplifies to not Y. The whole intermediate row is therefore Y, not Y. The final ket is still waiting on the right.', ['(X∧¬Y) ⇕ (¬X∧¬Y) = ¬Y','⟨X|M_{X⇒Y} = [Y,¬Y]'],[M('M_{X⇒Y}',LMI,mark=[0,1]),P('INTERMEDIATE ROW','[Y,¬Y]','Remaining ket: [Y,¬Y]ᵀ')],'Finish the row before contracting with the ket.'),
S('Finish the matched contraction','Contract that row with ket Y. Y AND Y is Y; not Y AND not Y is not Y. Their exclusive-or is always one. We have not asserted that every implication expression is true. This constant follows from the matched symbolic LM measurement we just computed.', ['⟨X|M_{X⇒Y}|Y⟩','= (Y∧Y) ⇕ (¬Y∧¬Y)','= Y⇕¬Y = 1'],[P('RESULT','Constant 1','For either value of X and Y'),P('DIFFERENT EXPRESSION','⟨X|[⇒]|Y⟩ = X⇒Y','That numeric-CM expression can be 0')],'A constant matched relation is different from an implication valuation.'),
S('Change the ket to its matched opposite','Keep the same bra and logical matrix, but use ket not Y. The intermediate row is unchanged. It now contracts with not Y, Y. Both products contain a value and its negation, so both vanish. The result is zero.', ['⟨X|M_{X⇒Y}|¬Y⟩','= (Y∧¬Y) ⇕ (¬Y∧Y) = 0'],[P('ROW','[Y,¬Y]'),P('NEW COLUMN','[¬Y,Y]ᵀ','Two zero products')],'The matched opposite picks the implication table’s failing relation.'),
S('Read all four matched relations','The four choices of X or not X on the left and Y or not Y on the right return the four numeric entries of implication. This is a property of the matched symbolic basis. It does not license substituting an unrelated expression without recalculation.', ['Matched measurements recover [⇒]'],[M('⇒',rows=['⟨X|','⟨¬X|'],cols=['|Y⟩','|¬Y⟩']),P('BASIS CHECK','⟨X|X⟩ = 1','⟨X|¬X⟩ = 0','The same identities hold for Y')],'Matched selectors recover the operator’s coefficients.'),
S('Your turn: use a different expression','Replace the right ket with ket Z, keeping the same X bra and the same implication logical matrix built from X and Y. Our intermediate row remains Y, not Y. What expression results when it meets Z, not Z?', ['[Y,¬Y] [Z,¬Z]ᵀ = ?'],[P('PAIR THE ENTRIES','Y with Z','¬Y with ¬Z'),P('REDUCE','AND each pair','XOR the two products')],'Pause: the new result may depend on Y and Z.',True),
S('Answer: an equivalence relation','The result is Y and Z exclusive-or not Y and not Z. Those terms are disjoint, and together they say that Y and Z agree. The measurement is now an expression, Y equivalent to Z, rather than the constant one from the matched case.', ['(Y∧Z) ⇕ (¬Y∧¬Z) = Y⇔Z'],[M('⇔',rows=['Y=1','Y=0'],cols=['Z=1','Z=0']),P('CHECK','Y=1,Z=1 gives 1','Y=1,Z=0 gives 0')],'Compute the intermediate vectors; distinguish matched constants from general formulas.')])

def tensor_expr(names):
    from itertools import product
    n=len(names)//2; labels=[''.join(map(str,b)) for b in product((1,0),repeat=n)]
    vals=[]
    for rb in product((1,0),repeat=n):
        row=[]
        for cb in product((1,0),repeat=n):
            row.append(''.join(('' if bit else '¬')+name for pair in zip(zip(names[::2],rb),zip(names[1::2],cb)) for name,bit in pair))
        vals.append(row)
    return vals,labels
T4,AX4=tensor_expr('WXYZ');T6,AX6=tensor_expr('ABCDEF')
lesson('larger_tensors','Generalize the tensor construction','Foundations 6–7 and lessons 15–16.','Paper §5.1–5.2, pp.19–23; explicit alternating axis order',[
S('Grow the layout without losing the address','Two variables give four assignments and fit a two-by-two matrix. Four variables give sixteen assignments and fit a four-by-four matrix. Six give sixty-four assignments and fit eight by eight. The key is to keep the row and column grouping explicit as the layout grows.', ['2 variables: 2×2     4 variables: 4×4','6 variables: 8×8'],[P('OUR GROUPING','Odd-position variables index rows','Even-position variables index columns'),P('ASSIGNMENT COUNT','2ᵏ cells for k independent bits','The shape follows the partition')],'A larger matrix needs an explicit variable-to-axis convention.'),
S('Recall one two-variable factor','For the conjunction W and X, the logical matrix is ket W times bra X. Its row components are W and not W; its columns are X and not X. A second factor for Y and Z follows the same pattern. Both complete factors are shown before we tensor them.', ['M_WX ⊗ M_YZ'],[M('M_WX',[['WX','W¬X'],['¬WX','¬W¬X']]),M('M_YZ',[['YZ','Y¬Z'],['¬YZ','¬Y¬Z']])],'Each factor is a complete 2×2 LM.'),
S('Read the full four-by-four result','The tensor row index combines W and Y; the column index combines X and Z. Each entry conjoins one expression from each factor. The upper-right cell contains W, not X, Y, not Z. Read the labelled components to see why each literal belongs there.', ['Rows: (W,Y)     Columns: (X,Z)'],[M('M_WX ⊗ M_YZ',T4,AX4,AX4,[0,3])],'The full 4×4 contains all sixteen conjunction patterns.'),
S('Add one more complete factor','Add the E F logical matrix to a tensor already containing A B and C D. Each dimension doubles. The rows now index A, C, E, and the columns index B, D, F. The displayed eight-by-eight overview shows the structure; we will enlarge one addressed entry next.', ['M_AB ⊗ M_CD ⊗ M_EF','Rows: (A,C,E)     Columns: (B,D,F)'],[M('6-variable conjunction LM',T6,AX6,AX6)],'Three 2×2 factors give one 8×8 tensor.'),
S('Zoom into one addressed entry','Choose row components one, zero, one and column components zero, one, zero. Those choices specify A true, C false, E true, and B false, D true, F false. Interleave them in the original variable order to get A, not B, not C, D, E, not F.', ['Row (A,C,E)=101     Column (B,D,F)=010','Entry = A¬B¬CDE¬F'],[P('ROW LITERALS','A','¬C','E'),P('COLUMN LITERALS','¬B','D','¬F')],'Read an addressed entry from the declared component order.'),
S('Separate conjunction basis from a general rule','The tensor shown is a conjunction basis LM. A general Boolean rule chooses a combination of basis matrices according to its truth values. For example, ANDing the three pairwise XOR rules uses the tensor of their numeric XOR CMs. Other outer operators require their own combination rule.', ['L = (A⇕B) ∧ (C⇕D) ∧ (E⇕F)','CM for this conjunction = [⇕]⊗[⇕]⊗[⇕]'],[M('⇕'),P('OUTER OPERATION','Here the three pairwise results are ANDed','A plain tensor represents this conjunction')],'Do not replace an arbitrary outer operator by a plain tensor.'),
S('Count dimensions with paired inputs','For two n independent input bits split evenly, there are n row bits and n column bits. That gives two to the n rows and two to the n columns. If the split is unequal, a rectangular matrix is equally valid; the complete assignment count is unchanged.', ['2n inputs: 2ⁿ×2ⁿ = 2²ⁿ cells','r row bits, c column bits: 2ʳ×2ᶜ'],[P('EXAMPLE','6 bits split 3+3: 8×8','6 bits split 2+4: 4×16'),P('SAME TOTAL','64 assignments','Different shapes')],'Count input bits separately from matrix dimensions.'),
S('Your turn: eight variables','Continue the alternating grouping with eight independent bits, A through H. Which variables index the rows? How many rows and columns are needed for an even split? Predict the shape before considering any particular Boolean operator.', ['A,B,C,D,E,F,G,H','Rows = ?     Columns = ?'],[P('PATTERN','Odd positions to rows','Even positions to columns')],'Pause and count the dimensions.',True),
S('Answer: sixteen by sixteen','The row bits are A, C, E, G; the column bits are B, D, F, H. Four bits on each axis require sixteen positions, giving two hundred fifty-six cells. Next we will transform a larger matrix while keeping its assignment mapping correct.', ['Rows: A,C,E,G     Columns: B,D,F,H','2⁴×2⁴ = 16×16 = 256 cells'],[P('KEEP VISIBLE','Axis variable order','Bit order within each axis'),P('NEXT','Permute a larger layout','Combine aligned larger CMs')],'Generalize tensors by tracking factors, axis order and assignment count.')])

def grid4(fn,rowvars=('W','Y'),colvars=('X','Z')):
    from itertools import product
    return [[int(fn(dict(zip(rowvars+colvars,rb+cb)))) for cb in product((1,0),repeat=2)] for rb in product((1,0),repeat=2)]
F4=lambda d:(not(d['W']^d['X'])) or ((not d['Y']) and d['Z'])
G4=lambda d:bool((d['Y'] and not d['Z']) ^ (not d['W']))
FG4=lambda d:(not F4(d)) or G4(d)
GAMMA1=grid4(F4);GAMMA2=grid4(G4);GAMMA=grid4(FG4)
lesson('larger_operations','Transform and combine larger CMs','Lessons 10–14 and 17; foundations 7.','Paper §5.3–5.4, pp.24–26; independent axis and truth-table verification',[
S('Keep a four-variable rule concrete','Our running rule is W exclusive-or X, implying not Y and Z. We use rows W Y and columns X Z, both true-first. Before transforming anything, read one assignment from this complete matrix and evaluate the original rule as a separate check.', ['F = (W⇕X) ⇒ (¬Y∧Z)','Rows WY     Columns XZ'],[M('Γ₁: CM of F',GAMMA1,AX4,AX4)],'Declare the full rule and the physical axes.'),
S('Check one cell against the formula','Let W be one, X zero, Y zero, and Z one. The antecedent is one exclusive-or zero, which is one. The consequent is not zero and one, also one. Implication gives one. Row W Y is one zero and column X Z is zero one.', ['WXYZ=1001','F = (1⇕0) ⇒ (¬0∧1) = 1⇒1 = 1'],[M('Γ₁',GAMMA1,AX4,AX4,[1,2]),M('⇒',mark=[0,0])],'The selected matrix cell and scalar expression agree.'),
S('Permute the row-bit order','Now display rows as Y W instead of W Y. Under true-first binary order, the middle two row addresses exchange places. New row zero-one reads old row one-zero. Columns remain X Z. This changes the presentation, provided we change the labels with the entries.', ['New rows YW: 11,10,01,00','Read old WY rows in order: 11,01,10,00'],[M('Γ₁ with rows YW',grid4(F4,('Y','W')),AX4,AX4,[2,2]),P('SAME ASSIGNMENT','W=1,Y=0','Old row WY=10','New row YW=01')],'Permute addresses and data together to preserve the rule.'),
S('Introduce a second rule in the same layout','Our second rule is the negation of Y and not Z being equivalent to not W. Negated equivalence is exclusive-or, so we can compute Y and not Z, exclusive-or not W. X is absent, but we still display the same W Y and X Z axes.', ['G = ¬((Y∧¬Z) ⇔ ¬W)','= (Y∧¬Z) ⇕ ¬W'],[M('Γ₂: CM of G',GAMMA2,AX4,AX4)],'An absent variable produces repeated entries, not a missing axis.'),
S('Combine matching assignments','To compute F implies G, apply implication to corresponding cells of their aligned matrices. At our chosen assignment, F is one and G is zero, so the combined result is zero. This operation is entrywise implication, not Boolean matrix multiplication.', ['H = F⇒G','Γ[i,j] = Γ₁[i,j] ⇒ Γ₂[i,j]'],[M('Γ₁',GAMMA1,AX4,AX4,[1,2]),M('Γ₂',GAMMA2,AX4,AX4,[1,2]),M('Γ',GAMMA,AX4,AX4,[1,2])],'Combine only cells that refer to the same assignment.'),
S('Verify all sixteen outputs','The completed matrix has one entry for each assignment of W, X, Y, and Z. We independently evaluate both original formulas, then their implication, for all sixteen assignments. This also catches a row-order mismatch that one convenient example could miss.', ['For each WXYZ: Γ[address] = (F⇒G)(WXYZ)'],[M('Verified Γ',GAMMA,AX4,AX4),P('CHECK METHOD','16 assignments','Scalar F and G computed separately','Compare every addressed cell')],'Exhaustive small checks validate the whole composition.'),
S('Your turn: when the first rule is false','Use W one, X zero, Y one, Z one. Find F and G, then F implies G. The antecedent of the outer implication may save you work, but check its value first. Locate row W Y one one and column X Z zero one.', ['WXYZ=1011     F⇒G = ?'],[M('Γ₁',GAMMA1,AX4,AX4,[0,2]),M('Γ₂',GAMMA2,AX4,AX4,[0,2])],'Pause and evaluate the outer implication.',True),
S('Answer: false implies false is true','The first rule is false because its antecedent is true and its consequent is false. The second rule is also false at this assignment. False implies false is true, so the combined cell is one. This agrees with the full matrix.', ['F=0     G=0     F⇒G=1'],[M('Γ',GAMMA,AX4,AX4,[0,2]),M('⇒',mark=[1,1])],'Align axes, apply the outer rule entrywise, and verify all assignments.')])

REPO=[[0,1,1,1],[0,1,1,1],[0,1,1,1],[1,0,0,0]]
RAX=['00','01','10','11']
lesson('cm_ir','Explicit CM versus the repository’s CM-IR','Foundations 8–9; formal algebra lessons optional.','cm_build.py; cm_ir.py compile_expr, CMNode, materialize_cm; shared Bible explicit-cm-vs-cm-ir',[
S('One rule, several different objects','The repository can represent one Boolean rule in several ways. Today we separate the expression we write, the compiled graph, and the explicit matrix of answers. Our example is A and B, exclusive-or C or D. These objects have different jobs even though they describe the same function.', ['L = (A∧B) ⇕ (C∨D)'],[P('EXPRESSION','Xor(And(A,B), Or(C,D))'),P('REPRESENTATIONS','Compiled expression graph','Explicit ordered truth matrix')],'A formula, a graph and a matrix are different artifacts.'),
S('Read the expression tree','The root operation is exclusive-or. Its left child computes A and B; its right child computes C or D. At the leaves are four variables. This tree describes how to compute a result. It does not yet contain a separate output cell for every possible assignment.', ['root: XOR','left: AND(A,B)     right: OR(C,D)'],[dict(label='EXPRESSION GRAPH',graph=True)],'Operations and dependencies describe a program.'),
S('Compile into a reusable graph','The public compile expression function builds a compiled object containing a node graph and an expression hash. The builder normalizes supported operations and can share repeated structure. Compilation prepares a representation that later evaluators or materializers can use; it is not itself a dense output matrix.', ['compiled = compile_expr(rule)'],[P('COMPILED OBJECT','compiled.node: CM-IR graph','compiled.expr_hash: expression key'),P('NEXT CHOICES','Evaluate in a supported mode','Materialize an ordered CM')],'Compilation prepares a reusable graph.'),
S('Materialize with a declared layout','To make a dense CM, declare row variables A B and column variables C D. The repository uses false-first binary order, zero-zero through one-one. That differs from the paper’s true-first examples. Each output cell is now the rule evaluated at one complete assignment.', ['Rows AB: 00,01,10,11','Columns CD: 00,01,10,11'],[M('Explicit CM for L',REPO,RAX,RAX)],'Repository arrays use false-first binary addressing.'),
S('Trace a graph computation into one cell','Choose A one, B one, C zero, D zero. AND produces one, OR produces zero, and the root exclusive-or produces one. This assignment selects row three and column zero in the repository layout. The same answer appears in that matrix cell.', ['L(1,1,0,0) = (1∧1)⇕(0∨0) = 1','row 11₂=3     column 00₂=0'],[M('Explicit CM',REPO,RAX,RAX,[3,0]),P('GRAPH VALUES','AND branch: 1','OR branch: 0','XOR root: 1')],'A graph evaluation and a matrix lookup can answer the same query.'),
S('Understand structural identity','An expression hash helps identify a stored expression structure. It is not a proof that all logically equivalent formulas have the same key. For example, distributivity gives two equivalent formulas with different expression structures. Their truth tables agree, but the repository’s expression hashes differ in our checked example.', ['A∧(B∨C) = (A∧B)∨(A∧C)'],[P('SEMANTIC CHECK','All 8 assignments agree'),P('STRUCTURAL CHECK','Different expression hashes','No global canonicality claim')],'Separate structural identity from logical equivalence.'),
S('Your turn: classify the artifact','Suppose you receive a sixteen-entry array together with the row and column variable lists. Is that an expression graph, an explicit CM, or merely a hash key? Identify the artifact by what it contains and what you can do with it.', ['16 stored answers + declared row/column lists'],[P('CHOOSE','Expression graph','Explicit CM','Hash key')],'Pause and classify the representation.',True),
S('Answer: the explicit matrix','The array with its axis lists is an explicit CM. It lets you address stored results. A graph stores operations and dependencies; a hash is an identity key. Next we will build this exact example using the actual public API, then validate every lookup.', ['Explicit CM = ordered array of truth values'],[M('Explicit CM',REPO,RAX,RAX),P('NEXT','Construct with Var(0), Var(1), …','Declare layouts','Check against a scalar oracle')],'Name the representation and output contract before discussing its behavior.')])

lesson('public_api','Build, query and validate a CM in code','Foundations 8–9 and lesson 19.','cm_exprlib.py; cm_build.py public API; runnable cm_advanced_examples_v1.py',[
S('Build a small example you can run','We will construct the four-input rule, build its matrix, and test every assignment. The accompanying Python example uses the current repository API. Start with four indexed variables; we call them A through D in the explanation, but their repository names are x zero through x three.', ['A,B,C,D = [Var(i) for i in range(4)]'],[P('IMPORTS','from cm_exprlib import Var, And, Or, Xor','from cm_build import compile_expr_to_cm','from cm_build import eval_cm_boolean')],'Use integer-indexed Var objects and explicit repository names.'),
S('Create the expression object','Construct AND from A and B, OR from C and D, then place both under XOR. This object records the expression structure. It does not rely on Python’s ordinary Boolean and operator, which would evaluate Python objects instead of building this expression tree.', ['rule = Xor(And(A,B), Or(C,D))'],[dict(label='EXPRESSION GRAPH',graph=True)],'Use the expression constructors to build the rule.'),
S('Declare the rows and columns','Choose x zero and x one as row variables, and x two and x three as column variables. The empty fixed dictionary means no input is held constant. With two free bits on each axis, the output has four rows and four columns.', ['R = ["x0","x1"]     C = ["x2","x3"]','M = compile_expr_to_cm(rule, R, C, {})'],[M('M: rows AB, columns CD',REPO,RAX,RAX)],'The variable lists define both membership and bit order.'),
S('Make a complete assignment explicit','For A one, B one, C zero, D zero, pass all four repository names in the assignment dictionary. Row bits one-one give index three; column bits zero-zero give index zero. The lookup returns one. Supplying every input avoids relying on any fallback behavior for missing names.', ['a = {"x0":1,"x1":1,"x2":0,"x3":0}','eval_cm_boolean(M, R, C, a, {}) = 1'],[M('M',REPO,RAX,RAX,[3,0])],'Use a complete assignment for a complete four-input query.'),
S('Check with an independent scalar oracle','Compute the expected answer directly from the four bits: A bitwise-AND B, exclusive-or C bitwise-OR D. Compare that with the lookup for every tuple from zero-zero-zero-zero to one-one-one-one. Sixteen checks cover the whole four-input function.', ['expected = (a & b) ^ (c | d)','assert lookup == expected'],[P('ORACLE','Plain scalar bit operations','Independent of matrix addressing'),P('COVERAGE','16 assignments','Every stored output checked')],'A separate oracle checks both values and addressing.'),
S('Try all three balanced layouts','Repeat with A C as rows and B D as columns, then A D as rows and B C as columns. The arrays move because the addressing changes. The same complete assignment must return the same result in every layout. Our runnable example checks all forty-eight layout-and-assignment combinations.', ['AB / CD     AC / BD     AD / BC'],[P('LAYOUT CHECK','3 layouts × 16 assignments','48 matching results'),P('KEEP ATTACHED','Row variable list','Column variable list','Complete assignment dictionary')],'Different layouts preserve the rule when their addressing is respected.'),
S('Reuse compilation when appropriate','The example also compiles the expression once with compile expression, then calls materialize C M on the compiled node for each layout. Those arrays match the direct compile-and-materialize calls. This separates reusable preparation from the requested final matrix output.', ['compiled = compile_expr(rule)','M = materialize_cm(compiled.node, R, C, {})'],[P('PREPARATION','Build the graph once'),P('OUTPUT','Materialize each requested layout','Compare with the direct API')],'Compilation reuse and output materialization are separate stages.'),
S('Your turn: address the same input differently','For A one, B zero, C one, D zero, use rows A C and columns B D. What row and column indices do you get, and what is the rule’s value? First split the bits according to the lists, then evaluate the scalar expression.', ['ABCD=1010     R=[A,C]     C=[B,D]'],[P('PREDICT','Row bits = ?','Column bits = ?','(A∧B)⇕(C∨D) = ?')],'Pause and solve both the address and the value.',True),
S('Answer: row three, column zero, value one','The row bits A C are one-one, giving three. The column bits B D are zero-zero, giving zero. AND is zero, OR is one, so exclusive-or is one. This is a small reproducible correctness example; it does not make a performance claim.', ['row=11₂=3     column=00₂=0','(1∧0)⇕(1∨0) = 0⇕1 = 1'],[P('RUNNABLE EXAMPLE','All three layouts','All sixteen assignments per layout','Exact assertions retained')],'Build through the public API and validate against a separate scalar oracle.')])

lesson('packed_outputs','Packed evaluation, execution choices and output cost','Lessons 19–20.','bitset_backend.py; cm_ir.py materialization modes; shared Bible packed-words-selection and eager-lazy',[
S('One function, different requested outputs','A single query asks for one bit. A count asks how many assignments return one. A full vector asks for every result in a declared order. These are different output contracts. Packed evaluation changes how many truth bits are stored and processed together, but does not erase those distinctions.', ['Point value     Count     Complete truth vector'],[P('RUNNING RULE','(A∧B)⇕(C∨D)'),P('OUTPUT QUESTIONS','Does this input satisfy it?','How many inputs satisfy it?','What are all the results?')],'Choose the output contract before choosing an execution path.'),
S('See the unpacked truth vector','In false-first assignment order, the first four outputs are zero, one, one, one. The next two groups repeat that pattern because A and B are not both true. The last four outputs are one, zero, zero, zero. The vector contains sixteen answers.', ['0000…0011: 0 1 1 1','0100…1011: 0 1 1 1  0 1 1 1','1100…1111: 1 0 0 0'],[P('ORDER CONTRACT','Assignment index increases from 0 to 15','A is the most significant input bit')],'A vector needs an assignment ordering, not just a length.'),
S('Pack each answer into its bit position','The backend defines bit k as the answer for assignment row k. In our example the packed integer is seven thousand nine hundred eighteen. Its low bit stores row zero, the next bit row one, and so on. Ordinary printed binary notation puts the highest bit on the left, so label the direction.', ['packed = Σ value[k] · 2ᵏ = 7918','bit 0 = value for assignment 0000'],[P('FIRST FOUR POSITIONS','k:       0 1 2 3','value:   0 1 1 1'),P('DO NOT CONFUSE','Assignment-bit order','Output bit-position order')],'Packed bit k corresponds to truth-table row k.'),
S('Operate on columns of truth bits','A packed evaluator constructs one bit column per input variable. Bitwise AND combines the A and B columns, OR combines C and D, and XOR combines those two results. Each bit position performs the same Boolean calculation for its own assignment.', ['packed_result = (A_bits & B_bits) ^ (C_bits | D_bits)'],[dict(label='SAME GRAPH, PACKED VALUES AT NODES',graph=True)],'Bitwise operations evaluate corresponding assignment positions.'),
S('Recover a count or unpack the vector','The packed integer has ten set bits, so the satisfying-assignment count is ten. Unpacking it produces the same sixteen-entry vector as the scalar oracle. Our example checks both facts. Counting after packed evaluation still requires that evaluation; it is not automatically a constant-time counting algorithm.', ['packed.bit_count() = 10','unpack(packed) = independently checked truth vector'],[P('CHECKED RESULTS','Packed integer: 7918','Set-bit count: 10','16 outputs match the oracle')],'A packed representation supports several outputs with different costs.'),
S('Separate storage from eager and lazy execution','Packed versus unpacked describes representation. Eager versus lazy describes when work is performed. The repository’s named evaluation and materialization modes have specific behavior, so we do not treat lazy as a promise that a requested full matrix is free. A materialize call still asks for a concrete array.', ['Representation: packed or unpacked','Execution: when intermediates are computed','Output: scalar, count, vector or matrix'],[P('DISTINCT DECISIONS','Storage layout','Evaluation strategy','Requested output')],'Do not equate packed storage with lazy execution.'),
S('Show when materialization happens','Compare two schedules for the same rule and layout. In the first, build the full matrix immediately and retain it for later lookup. In the second, keep the compiled graph and request the matrix later. Both schedules eventually return the same array; the distinction here is when the explicit output is produced.', ['Immediate: build graph; materialize now; retain array','Deferred: build graph; retain graph; materialize on demand'],[P('NOW','Immediate path has an explicit CM','Deferred path retains a graph'),P('ON OUTPUT REQUEST','Immediate path uses its array','Deferred path produces its array')],'Deferring an output postpones its construction rather than eliminating it.'),
S('Check the current lazy wrapper’s return value','Names alone can mislead. The current function named compile expression to C M lazy builds the shared graph and calls materialize C M before returning. Our example confirms that it returns the same dense array as the other wrapper. To defer final materialization explicitly, retain the compiled node and call materialize later.', ['compile_expr_to_cm_lazy(...) returns a dense array','Explicit deferral: retain compiled.node before materialize_cm(...)'],[P('CURRENT SOURCE CHECK','cm_build_lazy.py calls materialize_cm','Its returned object is an array'),P('EXAMPLE CHECK','Same layouts and inputs','Exact output equality')],'Verify the current API behavior instead of inferring it from its name.'),
S('The full output still grows exponentially','For k independent Boolean inputs, a complete truth vector has two to the k entries. Packing reduces storage overhead, but the mathematical output still contains that many bits. A graph may stay small while its explicit truth table becomes large. State which artifact a size claim describes.', ['k inputs ⇒ 2ᵏ truth bits','4 inputs: 16     20 inputs: 1,048,576'],[P('EXPLICIT OUTPUT','At least one bit per truth value','Plus representation overhead'),P('COMPACT PROGRAM','May describe many outputs','Does not itself list them')],'Packing does not remove the size of a requested complete output.'),
S('Your turn: name the output contract','A caller wants only to know whether one specified configuration is accepted. Another caller wants every accepted configuration listed. Are those the same benchmark task? Decide what must be returned before comparing their execution times.', ['One specified configuration     All accepted configurations'],[P('PREDICT','What must each call return?','Can the output sizes differ?')],'Pause and compare the requested results.',True),
S('Answer: the contracts are different','The first task returns one Boolean answer. The second must produce a potentially large list of assignments. Timing them as if they were equivalent would be misleading. Next we will define a fair comparison that accounts for preparation, repeated queries, and the exact output returned.', ['Compare equal workloads and equal outputs'],[P('FAIR COMPARISON','Same input set','Same result contract','Same preparation boundary')],'Distinguish representation, execution strategy and unavoidable output work.')])

lesson('fair_measurement','When preparation pays: a fair comparison','Lessons 19–21.','Shared Bible measurement-boundaries and exact-comparison-protocol; hypothetical arithmetic only',[
S('Does preparation save time overall?','A reusable representation can cost time to build before it answers any query. To decide whether that preparation pays off, compare total time for the same queries and the same output. We will use an explicitly hypothetical example to make the arithmetic transparent.', ['All timings in this lesson are HYPOTHETICAL'],[P('DIRECT METHOD','No separate preparation in this example'),P('PREPARED METHOD','One build cost','Then repeated queries')],'Compare total work for the same requested result.'),
S('Declare the model before calculating','Assume direct evaluation takes three milliseconds per query. The prepared method costs one hundred twenty milliseconds to build and half a millisecond per query. Both return the same single Boolean answer for each input. These numbers illustrate a method; they are not measurements of this repository.', ['Direct: 3 ms/query','Prepared: 120 ms build + 0.5 ms/query'],[P('CONTROLLED ASSUMPTIONS','Same Boolean query','Same input workload','No hidden output conversion')],'Label illustrative numbers before using them.'),
S('Write the total-cost equations','Let N be the number of queries. Direct evaluation costs three N milliseconds. The prepared path costs one hundred twenty plus half N. The build cost is paid once only if the prepared artifact can actually be reused across those queries.', ['T_direct(N) = 3N ms','T_prepared(N) = 120 + 0.5N ms'],[P('FIXED COST','120 ms once'),P('REPEATED COST','0.5 ms for each query')],'Separate one-time preparation from recurring query work.'),
S('Solve the break-even point','Set the two costs equal. Subtract half N from both sides, giving two and a half N equals one hundred twenty. Divide to obtain forty-eight queries. At exactly forty-eight, both paths take one hundred forty-four milliseconds under our assumptions.', ['3N = 120 + 0.5N','2.5N = 120     N = 48','Both totals: 144 ms'],[P('BREAK-EVEN','48 queries','Equality, not yet a strict win')],'Break-even includes the one-time build cost.'),
S('Check below and above the crossover','At ten queries, direct evaluation takes thirty milliseconds, while preparation plus queries takes one hundred twenty-five. At one hundred queries, direct takes three hundred and prepared takes one hundred seventy. The preferable path changes with reuse, even though each prepared query is faster.', ['N=10: direct 30 ms; prepared 125 ms','N=100: direct 300 ms; prepared 170 ms'],[P('LOW REUSE','Build cost dominates'),P('HIGHER REUSE','Query savings can repay preparation')],'A faster query kernel need not mean a faster end-to-end task.'),
S('Plan a real measurement boundary','A real experiment must say whether parsing, compilation, caches, conversion, and final output are included. Use the same inputs, verify results first, and report repeated measurements with host and software details. A warm cached run and a cold run answer different questions.', ['parse + compile + evaluate + convert + return'],[P('RECORD','Host and source revision','Warm or cold state','Workload and repetitions'),P('VERIFY','Equal answers','Equal requested outputs','Same timing boundary')],'A timing result is meaningful only with its boundary and workload.'),
S('Your turn: the first strict improvement','In our hypothetical model, equality occurs at forty-eight queries. What is the smallest whole number of queries for which the prepared method is strictly faster? Calculate both totals there rather than rounding the equality point into a claimed win.', ['N = ?     T_prepared < T_direct'],[P('USE','T_direct = 3N','T_prepared = 120 + 0.5N')],'Pause and find the first strict improvement.',True),
S('Answer: forty-nine queries','At forty-nine queries, the direct total is one hundred forty-seven milliseconds. The prepared total is one hundred forty-four and a half. That is the first whole-query count with a strict improvement in this model. Different build or query costs would change the crossover.', ['N=49: 147 ms versus 144.5 ms'],[P('RESULT','Prepared is faster by 2.5 ms','Under the stated hypothetical model')],'Evaluate preparation tradeoffs with declared costs and matching output contracts.')])

POLICY=[[0,0,0,0],[0,0,0,0],[0,0,1,0],[1,0,1,0]]
lesson('application','A small end-to-end access-policy example','Lessons 20–22.','Current repository public API; original bounded teaching example; no deployment',[
S('Turn a plain-language policy into a question','Consider a small document-access rule. A person must be authenticated, must be either the owner or an administrator, and must not be suspended. We will formalize this rule, compile it, test every input, and state exactly what our example does and does not establish.', ['allow = authenticated ∧ (owner∨admin) ∧ ¬suspended'],[P('FOUR INPUT BITS','A: authenticated','O: owner','D: administrator','S: suspended')],'Start with a precise Boolean question.'),
S('Choose the output contract','Our query returns one bit: allow or deny for one specified combination of the four facts. For teaching and exhaustive checking, we will also materialize all sixteen answers. The rule does not verify identity or decide whether someone really is an administrator; those facts must come from a trusted surrounding system.', ['Query output: one allow/deny bit','Teaching artifact: all 16 answers'],[P('INPUT RESPONSIBILITY','Obtain the four facts correctly'),P('RULE RESPONSIBILITY','Combine the supplied facts','Return a Boolean decision')],'Define the boundary between facts and the Boolean rule.'),
S('Build the expression with the public API','Map the four facts to Var zero through Var three. Build owner OR administrator, AND that with authenticated, then AND the result with NOT suspended. The grouping follows the plain-language policy. Parentheses make the intended structure explicit.', ['A,O,D,S = [Var(i) for i in range(4)]','policy = And(And(A, Or(O,D)), Not(S))'],[P('VARIABLE MAP','x0=A    x1=O','x2=D    x3=S'),P('ORDER OF WORK','Owner or administrator','Require authentication','Exclude suspension')],'Construct the policy with explicit grouping and variable names.'),
S('Compile and materialize the small truth layout','Compile the policy once, then materialize rows authenticated-owner and columns administrator-suspended. In false-first order, the first two rows are all zero because authentication is absent. Only three of the sixteen complete assignments are accepted. We will inspect why, rather than treating the matrix as a black box.', ['Rows AO     Columns DS     false-first'],[M('Policy CM',POLICY,RAX,RAX)],'A fully labelled matrix makes the policy’s behavior inspectable.'),
S('Trace an allowed administrator case','Take authenticated one, owner zero, administrator one, suspended zero. Owner OR administrator gives one. Authentication is present and suspension is absent, so the final result is one. This is row one-zero and column one-zero, or row two and column two in binary addressing.', ['AODS=1010','allow = 1∧(0∨1)∧¬0 = 1'],[M('Policy CM',POLICY,RAX,RAX,[2,2]),P('CHECK THE GATES','Authenticated: yes','Owner or admin: yes','Not suspended: yes')],'Explain a selected cell through the original policy.'),
S('Change one fact: suspension','Keep that same administrator case, but change suspended to one. The first two requirements still pass, but not suspended is now zero. The whole conjunction becomes zero. The highlighted cell moves one column to the right and changes from allow to deny.', ['AODS=1011','allow = 1∧(0∨1)∧¬1 = 0'],[M('Policy CM',POLICY,RAX,RAX,[2,3]),P('CHANGED FACT','S changed from 0 to 1','The exclusion gate now fails')],'Changing one input should have an explainable effect.'),
S('Validate the policy exhaustively','Our separate scalar oracle evaluates authenticated AND owner-or-administrator AND not-suspended for every four-bit assignment. Every matrix lookup matches. Three cases are allowed: authenticated, not suspended, and at least one of owner or administrator. The other thirteen are denied.', ['16 assignments checked     3 allow     13 deny'],[M('Verified policy CM',POLICY,RAX,RAX),P('ORACLE','a and (o or d) and not s','Independent of matrix addressing')],'Exhaustive checking is practical for this bounded four-bit example.'),
S('Your turn: does ownership override suspension?','Suppose the person is authenticated and is the owner, is not an administrator, and is suspended. Should the policy allow access? Use the expression as written, not a different policy you might prefer. Identify which requirement decides the result.', ['AODS=1101     allow = ?'],[M('Policy CM',POLICY,RAX,RAX,[3,1]),P('PREDICT','Authentication passes','Ownership passes','What does suspension do?')],'Pause and evaluate the policy as specified.',True),
S('Answer: suspension still denies access','The not-suspended factor is zero, so the result is deny even for an authenticated owner. If ownership were meant to override suspension, that would be a different policy expression requiring new tests. This example implements the stated rule, not a universal access-control design.', ['1∧(1∨0)∧¬1 = 0'],[M('Policy CM',POLICY,RAX,RAX,[3,1]),P('SPECIFICATION MATTERS','A changed policy means a changed formula','Recheck every assignment after a change')],'Tests establish agreement with the specified rule.'),
S('Retain what makes the result reproducible','Keep the expression, variable map, axis ordering, compiled representation when useful, and validation results. This local example makes no deployment or security claim and no benchmark claim. Across the series, the same habit has mattered: define the object, show the operation, and verify the result against its meaning.', ['Retain: rule + names + layout + oracle checks'],[P('DELIVERED WITH THE LESSON','Runnable repository example','Complete small truth-table checks','Source and output-contract notes')],'Build a bounded CM application with explicit inputs, outputs and exhaustive verification.')])

def export():
    OUT.mkdir(parents=True,exist_ok=True)
    (OUT/'CURRICULUM_V1.json').write_text(json.dumps(LESSONS,ensure_ascii=False,indent=2),encoding='utf-8')
    for l in LESSONS:
        f=OUT/l['id'];f.mkdir(exist_ok=True)
        lines=[f"# {l['title']}",'',f"Prerequisite: {l['prerequisite']}",'',f"Source: {l['source']}"]
        for i,s in enumerate(l['scenes'],1):
            lines += ['',f"## {i}. {s['title']}",'',s['text'],'','Displayed calculation:','',*s['equations'],'',f"Takeaway: {s['note']}",'','Visual data:',json.dumps(s['cards'],ensure_ascii=False)]
            if s.get('pause'):lines+=['','Five-second answer-withheld practice pause.']
        (f/'SCRIPT_AND_VISUAL_SPEC_V1.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    print(json.dumps(dict(lessons=len(LESSONS),scenes=sum(len(l['scenes']) for l in LESSONS),characters=sum(len('\n\n'.join(s['text'] for s in l['scenes'])) for l in LESSONS))))
if __name__=='__main__':export()
