from __future__ import annotations

import csv
import hashlib
import json
import re
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DATA = REPO / "deliverables_n22_24"
OUTPUT = DATA / "v4audit_public_chart_data_2026_07_24.js"


def _rows(name: str):
    with (DATA / name).open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _sha(name: str):
    return hashlib.sha256((DATA / name).read_bytes()).hexdigest()


def _source_revision(names: list[str]) -> str | None:
    """Return the last commit that changed any chart input.

    Using HEAD here makes the generated file stale as soon as the file itself
    is committed. Tying provenance to the inputs keeps regeneration
    deterministic while still identifying the revision behind the chart data.
    """
    try:
        return subprocess.check_output(
            ["git", "log", "-1", "--format=%H", "--", *names],
            cwd=REPO,
            text=True,
        ).strip() or None
    except Exception:
        return None


def build_chart_data():
    f1_name = "CM_V3AUDIT_F1_words_timing.csv"
    f1 = [r for r in _rows(f1_name) if r["interpreter"] == "3.13.5" and int(r["n"]) >= 16]
    kernel_n = [int(r["n"]) for r in f1]
    bigint = [round(float(r["bigint_cm_us"]) / float(r["bigint_raw_us"]), 2) for r in f1]
    words = [round(float(r["words_cm_us"]) / float(r["words_raw_us"]), 2) for r in f1]

    report_name = "CM_FABLE_BENCHMARKS_2026-07-21.md"
    report = (DATA / report_name).read_text(encoding="utf-8")
    match = re.search(r"Audit V3's paired rerun\s*([0-9./]+) through n=24", report)
    if not match:
        raise ValueError("could not extract the documented Audit V3 wrapper series")
    wrapper_prefix = [float(x) for x in match.group(1).split("/")]
    extended_name = "CM_FABLE_extended_n32_summary.csv"
    extended = [
        r for r in _rows(extended_name)
        if int(r["depth"]) == 4 and int(r["n"]) >= 26
    ]
    wrapper = wrapper_prefix + [round(float(r["ratio_median"]), 2) for r in extended]

    cudd_name = "CM_FABLE_cudd_wrapper32_summary.csv"
    cudd_rows = _rows(cudd_name)
    cudd = [round(float(r["ratio_cudd_build_bitset_median"]), 2) for r in cudd_rows]

    corrected_name = "CM_V3AUDIT_F5_corrected_all_live_summary.csv"
    corrected_rows = _rows(corrected_name)
    corrected_by_n = {
        int(r["n"]): round(float(r["cm_over_bitset_median"]), 2)
        for r in corrected_rows
    }
    beyond_name = "CM_FABLE_comprehensive_beyondguard.csv"
    beyond_rows = _rows(beyond_name)
    beyond_by_n = {}
    for n in (24, 28, 32):
        values = sorted(float(r["ratio_words"]) for r in beyond_rows if int(r["n"]) == n)
        mid = len(values) // 2
        median = values[mid] if len(values) % 2 else (values[mid - 1] + values[mid]) / 2
        beyond_by_n[n] = round(median, 2)

    all_n = [16, 18, 20, 22, 24, 26, 28, 30, 32]
    source_names = [
        f"deliverables_n22_24/{name}"
        for name in (
            f1_name,
            report_name,
            extended_name,
            cudd_name,
            corrected_name,
            beyond_name,
        )
    ]
    return {
        "schema_version": 1,
        "source_revision": _source_revision(source_names),
        "kernel": {
            "n": kernel_n,
            "bigint_engine": bigint,
            "words_engine": words,
        },
        "wrapper": {
            "n": all_n,
            "cm_over_bitset": wrapper,
            "cudd_build_over_bitset_contextual": cudd,
        },
        "frontier": {
            "n": all_n,
            "corrected_all_live": [corrected_by_n.get(n) for n in all_n],
            "beyond_guard_support": [beyond_by_n.get(n) for n in all_n],
        },
        "sources": {
            f1_name: {"sha256": _sha(f1_name), "rule": "Python 3.13.5 CM median / raw median, rounded 2dp"},
            report_name: {"sha256": _sha(report_name), "rule": "documented Audit V3 paired rerun n=16..24"},
            extended_name: {"sha256": _sha(extended_name), "rule": "depth=4 ratio_median n=26..32, rounded 2dp"},
            cudd_name: {"sha256": _sha(cudd_name), "rule": "ratio_cudd_build_bitset_median, rounded 2dp; contextual metric"},
            corrected_name: {"sha256": _sha(corrected_name), "rule": "cm_over_bitset_median, rounded 2dp"},
            beyond_name: {"sha256": _sha(beyond_name), "rule": "median ratio_words by n, rounded 2dp"},
        },
    }


def render_javascript():
    payload = json.dumps(build_chart_data(), sort_keys=True, indent=2)
    return "// Generated by scripts/generate_v4audit_public_chart_data.py; do not hand edit.\n" f"const V4AUDIT_CHART_DATA = {payload};\n"


def main():
    OUTPUT.write_text(render_javascript(), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
